project:
  type: website
  output-dir: _site

execute:
  freeze: auto 

website:
  title: "BEM2031 2024-25"
  image: "quarto_2024_25/images/welcome.png"
  favicon: "quarto_2024_25/images/bulb2.png"
  repo-url: https://github.com/AliHarp/BEM2031-24-25
  repo-actions: [edit, issue]
  page-navigation: true
  page-footer:
    left:  |
      [University of Exeter](https://www.exeter.ac.uk/study/studyinformation/modules/info/?moduleCode=BEM2031&ay=2024/5&sys=0)
    center:     
      - text: "License"
        href: quarto_2024_25/license.qmd
    right:
      - icon: github
        href: https://github.com/AliHarp/BEM2031-24-25
  navbar:
    logo: "quarto_2024_25/images/bulb3.png"
    left:
      - href: index.qmd
        text: Welcome
      - about.qmd
  sidebar:
    style: "floating"
    background: "#d7ebf5"
    alignment: center
    collapse-level: 1
    contents:
      - text: "MODULE MATERIALS"
      - section: "Lecture slides"
        contents: 
          - quarto_2024_25/Weekly_lectures/L1.qmd
          - quarto_2024_25/Weekly_lectures/L2.qmd
          - quarto_2024_25/Weekly_lectures/L3.qmd

      - section: "Workshop output files"
        contents:
          - quarto_2024_25/Weekly_seminars/S1.qmd
          - quarto_2024_25/Weekly_seminars/S2.qmd
          - quarto_2024_25/Weekly_seminars/S3.qmd
          - quarto_2024_25/Weekly_seminars/S4.qmd

      - section: "Workshop interactive code"
        contents:
          - quarto_2024_25/Live_code/live_q.qmd
          - quarto_2024_25/Live_code/lv.qmd
          - quarto_2024_25/Live_code/week3.qmd











format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

